steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run', 'fetch']
    env:
      - 'GH_TOKEN=$_GH_TOKEN'
  - name: node
    entrypoint: npm
    args: ['run', 'aggregate']
  - name: node
    entrypoint: npm
    args: ['run', 'refresh']
    env:
      - 'SPREADSHEET_ID=$_SPREADSHEET_ID'
      - 'CREDENTIALS=$_CREDENTIALS'
      - 'TOKEN=$_TOKEN'
