steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run', 'fetch']
    env:
      - 'GH_TOKEN=$_GH_TOKEN'
    timeout: 1200s
  - name: node
    entrypoint: npm
    args: ['run', 'aggregate']
  - name: node
    entrypoint: npm
    args: ['run', 'refresh']
    env:
    - 'SPREADSHEET_ID=$_SPREADSHEET_ID'
    - 'CREDENTIALS=$_CREDENTIALS'
    - 'TOKEN=$_TOKEN'
    timeout: 1200s

